projekat/app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('movies/', views.movies, name='movies'),
    path('movies/<int:id>/', views.movie, name='movie'),
    path('movie/edit/<int:id>/', views.edit, name='edit'),
    path('movie/new/', views.new, name='new'),
    path('movie/delete/<int:id>/', views.delete, name='delete')
]

projekat/projekat/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name = 'signup'),
    path('', include('app.urls')),

]

projekat/app/models.py
from django.db import models
from django.contrib.auth.models import User


class Movie(models.Model):
    title = models.CharField(max_length=64)
    review = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title + ': ' + self.review

projekat/app/forms.py
from django.forms import ModelForm
from .models import Movie


class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = ['title', 'review']

projekat/app/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect, get_object_or_404

from django.http import HttpResponse

# Create your views here.
from .models import Movie
from .forms import MovieForm


def index(request):
    if not request.user.is_authenticated:
        return render(request, 'index.html', {'page_title': 'Home'})
    else:
        return redirect('app:movies')


@login_required
def movies(request):
    tmp = Movie.objects.all()
    return render(request, 'movies.html', {'movies': tmp})


@login_required
def movie(request, id):
    tmp = get_object_or_404(Movie, id=id)
    return render(request, 'movie.html', {'movie': tmp, 'page_title': tmp.title})


@permission_required('app.change_movie')
def edit(request, id):
    if request.method == 'POST':
        form = MovieForm(request.POST)

        if form.is_valid():
            a = Movie.objects.get(id=id)
            a.title = form.cleaned_data['title']
            a.review = form.cleaned_data['review']
            a.save()
            return redirect('app:movies')
        else:
            return render(request, 'edit.html', {'form': form, 'id': id})
    else:
        a = Movie.objects.get(id=id)
        form = MovieForm(instance=a)
        return render(request, 'edit.html', {'form': form, 'id': id})


@permission_required('app.delete_movie')
def delete(request, id):
    a = Movie.objects.get(id=id)
    a.delete()
    tmp = Movie.objects.all()
    return render(request, 'movies.html', {'movies': tmp})


@permission_required('app.add_movie')
def new(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)

        if form.is_valid():
            a = Movie(title=form.cleaned_data['title'], review=form.cleaned_data['review'], owner=request.user)
            a.save()
            return redirect('app:movies')
        else:
            return render(request, 'new.html', {'form': form})
    else:
        form = MovieForm()
        return render(request, 'new.html', {'form': form})

projekat/projekat/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/movies')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

projekat/app/templates/edit.html
{% extends 'master.html' %}

{% block title %}
    Edit movie
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'app:edit' id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.name }}" value="{{ form.title.value }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.review.id_for_label }}">{{ form.review.label_tag }}</label>
            <textarea class="form-control" id="{{ form.review.id_for_label }}" name="{{ form.review.name }}" rows="5">{{ form.review.value }}</textarea>
            {% if form.review.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.review.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Save"/>
    </form>

{% endblock %}

projekat/app/templates/index.html
{%  extends 'master.html' %}

{%  block content %}
    <p>You are not logged in.</p>
    <a href="{% url 'login'%}">Click here to login.</a>
{% endblock %}

projekat/app/templates/movie.html
{% extends 'master.html' %}

{% block content %}

    <div class="card">
        <div class="card-header">
            <h1>
                {{ movie.title }}
                {% if perms.app.change_movie %}
                    <a href="{% url 'app:edit' movie.id %}">
                        <span class="badge badge-primary">Edit</span>
                    </a>
                {% endif %}
                {% if perms.app.delete_movie %}
                    <a href="{% url 'app:delete' movie.id %}">
                        <span class="badge badge-primary">Delete</span>
                    </a>
                {% endif %}
            </h1>
        </div>
    </div>
    <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>{{ movie.review }}</p>
                <footer class="blockquote-footer">
                    Author:
                    <cite title="Source Title">
                        {{ movie.owner.username }}
                    </cite>
                </footer>
            </blockquote>
        </div>
    </div>

{% endblock %}

projekat/app/templates/movies.html
{%  extends 'master.html' %}

{% block title %}
    Movies
{% endblock %}

{%  block content %}
    <div class="list-group">
        {% for movie in movies %}
            <a class="list-group-item list-group-item-action" href="{% url 'app:movie' movie.id %}">
                {{ movie.title }}
            </a>
        {% endfor %}
    </div>
{% endblock %}

projekat/app/templates/new.html
{% extends 'master.html' %}

{% block title %}
    New movie
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'app:new' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.name }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.review.id_for_label }}">{{ form.review.label_tag }}</label>
            <textarea class="form-control" id="{{ form.review.id_for_label }}" name="{{ form.review.name }}" rows="5"></textarea>
            {% if form.review.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.review.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Add"/>
    </form>

{% endblock %}

projekat/templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'app:movies' %}">
        <img src="{% static 'img/cinema.png' %}" width="30" height="30" class="d-inline-block align-top" alt="logo"/>
        Luka's Movie Reviews
    </a>

    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            {% if not perms.demo_app.add_article %}
                <a class="nav-link disabled" href="{% url 'app:new' %}">New movie</a>
            {% else %}
                <a class="nav-link" href="{% url 'app:new' %}">New movie</a>
            {% endif %}
        </li>
    </ul>

    {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Logout {{ user.get_username }}</a>
    {% else %}
        <a class="nav-link" href="{% url 'signup' %}">Register</a>
    {% endif %}

</nav>

projekat/templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>
            {% block title %}
                {{ page_title|default:"Untitled Page" }}
            {% endblock title %}
        </title>

        <link rel="shortcut icon" type="image/png" href="{% static 'shortcut.png' %}"/>

        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    </head>

    <body>

        {% include 'header.html' %}

        <div class="container" style="text-align: center; margin-top: 50px">
            {% block content %}
                <p>Placeholder text in base template. Replace with page content.</p>
            {% endblock content %}
        </div>

    </body>
</html>

projekat/templates/signup.html
{% extends 'master.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}